### ISSUE TITLE
Fallback should check that name is valid

### ISSUE THREAD

**Issue by passcod** [zkat/npx#115]
This popped out from a mistake I made:

```
$ :i 'dared dream'
:i not found. Trying with npx...
/home/.local/share/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:265
      throw invalidTagName(spec)
      ^

Error: Invalid tag name ":i": Tags may not have any characters that encodeURIComponent encodes.
    at invalidTagName (/home/.local/share/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:76:15)
    at fromRegistry (/home/.local/share/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:265:13)
    at resolve (/home/.local/share/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:66:12)
    at npa (/home/.local/share/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:39:10)
    at Function.parseArgs (/home/.local/share/lib/node_modules/npm/node_modules/libnpx/parse-args.js:48:23)
    at Object.<anonymous> (/home/.local/share/lib/node_modules/npm/bin/npx-cli.js:8:9)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
```

(on another system, `:i` is a shortcut to perform a case insensitive search)

While this error is probably fine as is (although it could be helped by a coat of paint / better messaging) in the `$ npx name` variant, it's not great in the fallback way. We probably should check that the command tried is a valid npm package name, and if it's not, just skip npx silently.

**Comment by zkat** [comment]
@passcod how do you feel about putting together a patch for this one? :)

**Comment by passcod** [comment]
I'll try if I have time this weekend. If I haven't chimed back by Tuesday UTC, assume I'm not :)
