### ISSUE TITLE
Please update yargs to 10.0

### ISSUE THREAD

**Issue by pravi** [zkat/npx#139]
We'd like to use yargs 10.0 in debian and it would be good to fix these errors when updating to yargs 10.0.3.

```
TAP version 13
# Subtest: test/parse-args.js
    # Subtest: parses basic command
        ok 1 - should be equal
        ok 2 - should be equivalent
        ok 3 - should be equal
        ok 4 - should be equal
        ok 5 - should be equal
        ok 6 - should be equivalent
        1..6
    ok 1 - parses basic command # time=11.282ms
    
    # Subtest: parses command with version
        ok 1 - should be equal
        ok 2 - should be equivalent
        ok 3 - should be equal
        ok 4 - should be equal
        1..4
    ok 2 - parses command with version # time=24.732ms
    
    # Subtest: parses command opts
        ok 1 - should be equal
        ok 2 - should be equivalent
        ok 3 - should be equal
        ok 4 - should be equal
        ok 5 - should be equivalent
        1..5
    ok 3 - parses command opts # time=3.814ms
    
    # Subtest: parses scoped package command opts
        ok 1 - should be equal
        ok 2 - should be equivalent
        ok 3 - should be equal
        ok 4 - should be equal
        ok 5 - should be equivalent
        1..5
    ok 4 - parses scoped package command opts # time=6.958ms
    
    # Subtest: ignores options after command
        ok 1 - should be equal
        ok 2 - should be equivalent
        ok 3 - should be equal
        ok 4 - should be equal
        ok 5 - should be equivalent
        1..5
    ok 5 - ignores options after command # time=2.433ms
    
YError: Invalid first argument. Expected boolean or string but received function.
    at argumentTypeError (/home/praveen/npx/node_modules/yargs/lib/argsert.js:65:9)
    at parsed.optional.forEach (/home/praveen/npx/node_modules/yargs/lib/argsert.js:47:39)
    at Array.forEach (native)
    at argsert (/home/praveen/npx/node_modules/yargs/lib/argsert.js:42:21)
    at Object.version (/home/praveen/npx/node_modules/yargs/yargs.js:757:5)
    at yargsParser (/home/praveen/npx/parse-args.js:226:4)
    at parseArgs (/home/praveen/npx/parse-args.js:16:18)
    at mockParse (/home/praveen/npx/test/parse-args.js:8:10)
    at Test.t (/home/praveen/npx/test/parse-args.js:62:18)
    at bound (domain.js:280:14)
    at Test.runBound (domain.js:293:12)
    at Test.main (/home/praveen/npx/node_modules/tap/lib/test.js:219:20)
    at TAP.Test.writeSubComment (/home/praveen/npx/node_modules/tap/lib/test.js:354:3)
    at loop (/home/praveen/npx/node_modules/function-loop/index.js:35:15)
    at TAP.Test.runBeforeEach (/home/praveen/npx/node_modules/tap/lib/test.js:678:5)
    at TAP.Test.processSubtest (/home/praveen/npx/node_modules/tap/lib/test.js:318:10)
    # Subtest: assumes unknown args before cmd have values and ignores them
        ok 1 - should be equal
        ok 2 - should be equivalent
        ok 3 - should be equal
        ok 4 - should be equal
        ok 5 - should be equivalent
        1..5
    ok 6 - assumes unknown args before cmd have values and ignores them # time=69.498ms
    
YError: Invalid first argument. Expected boolean or string but received function.
    at argumentTypeError (/home/praveen/npx/node_modules/yargs/lib/argsert.js:65:9)
    at parsed.optional.forEach (/home/praveen/npx/node_modules/yargs/lib/argsert.js:47:39)
    at Array.forEach (native)
    at argsert (/home/praveen/npx/node_modules/yargs/lib/argsert.js:42:21)
    at Object.version (/home/praveen/npx/node_modules/yargs/yargs.js:757:5)
    at yargsParser (/home/praveen/npx/parse-args.js:226:4)
    at parseArgs (/home/praveen/npx/parse-args.js:16:18)
    at mockParse (/home/praveen/npx/test/parse-args.js:8:10)
    at Test.t (/home/praveen/npx/test/parse-args.js:72:18)
    at bound (domain.js:280:14)
    at Test.runBound (domain.js:293:12)
    at Test.main (/home/praveen/npx/node_modules/tap/lib/test.js:219:20)
    at TAP.Test.writeSubComment (/home/praveen/npx/node_modules/tap/lib/test.js:354:3)
    at loop (/home/praveen/npx/node_modules/function-loop/index.js:35:15)
    at TAP.Test.runBeforeEach (/home/praveen/npx/node_modules/tap/lib/test.js:678:5)
    at TAP.Test.processSubtest (/home/praveen/npx/node_modules/tap/lib/test.js:318:10)
    # Subtest: parses package option
        ok 1 - should be equal
        ok 2 - should be equivalent
        ok 3 - should be equal
        ok 4 - should be equal
        ok 5 - should be equivalent
        1..5
    ok 7 - parses package option # time=11.667ms
    
YError: Invalid first argument. Expected boolean or string but received function.
    at argumentTypeError (/home/praveen/npx/node_modules/yargs/lib/argsert.js:65:9)
    at parsed.optional.forEach (/home/praveen/npx/node_modules/yargs/lib/argsert.js:47:39)
    at Array.forEach (native)
    at argsert (/home/praveen/npx/node_modules/yargs/lib/argsert.js:42:21)
    at Object.version (/home/praveen/npx/node_modules/yargs/yargs.js:757:5)
    at yargsParser (/home/praveen/npx/parse-args.js:226:4)
    at parseArgs (/home/praveen/npx/parse-args.js:16:18)
    at mockParse (/home/praveen/npx/test/parse-args.js:8:10)
    at Test.t (/home/praveen/npx/test/parse-args.js:82:18)
    at bound (domain.js:280:14)
    at Test.runBound (domain.js:293:12)
    at Test.main (/home/praveen/npx/node_modules/tap/lib/test.js:219:20)
    at TAP.Test.writeSubComment (/home/praveen/npx/node_modules/tap/lib/test.js:354:3)
    at loop (/home/praveen/npx/node_modules/function-loop/index.js:35:15)
    at TAP.Test.runBeforeEach (/home/praveen/npx/node_modules/tap/lib/test.js:678:5)
    at TAP.Test.processSubtest (/home/praveen/npx/node_modules/tap/lib/test.js:318:10)
    # Subtest: parses multiple package options
        ok 1 - should be equal
        ok 2 - should be equivalent
        ok 3 - should be equal
        ok 4 - should be equal
        ok 5 - should be equivalent
        1..5
    ok 8 - parses multiple package options # time=13.299ms
    
YError: Invalid first argument. Expected boolean or string but received function.
    at argumentTypeError (/home/praveen/npx/node_modules/yargs/lib/argsert.js:65:9)
    at parsed.optional.forEach (/home/praveen/npx/node_modules/yargs/lib/argsert.js:47:39)
    at Array.forEach (native)
    at argsert (/home/praveen/npx/node_modules/yargs/lib/argsert.js:42:21)
    at Object.version (/home/praveen/npx/node_modules/yargs/yargs.js:757:5)
    at yargsParser (/home/praveen/npx/parse-args.js:226:4)
    at parseArgs (/home/praveen/npx/parse-args.js:16:18)
    at mockParse (/home/praveen/npx/test/parse-args.js:8:10)
    at Test.t (/home/praveen/npx/test/parse-args.js:92:18)
    at bound (domain.js:280:14)
    at Test.runBound (domain.js:293:12)
    at Test.main (/home/praveen/npx/node_modules/tap/lib/test.js:219:20)
    at TAP.Test.writeSubComment (/home/praveen/npx/node_modules/tap/lib/test.js:354:3)
    at loop (/home/praveen/npx/node_modules/function-loop/index.js:35:15)
    at TAP.Test.runBeforeEach (/home/praveen/npx/node_modules/tap/lib/test.js:678:5)
    at TAP.Test.processSubtest (/home/praveen/npx/node_modules/tap/lib/test.js:318:10)
    # Subtest: does not parse -c
        ok 1 - stays unparsed
        ok 2 - should be equivalent
        ok 3 - should be equal
        ok 4 - should be equal
        ok 5 - should be equivalent
        1..5
    ok 9 - does not parse -c # time=11.319ms
    
YError: Invalid first argument. Expected boolean or string but received function.
    at argumentTypeError (/home/praveen/npx/node_modules/yargs/lib/argsert.js:65:9)
    at parsed.optional.forEach (/home/praveen/npx/node_modules/yargs/lib/argsert.js:47:39)
    at Array.forEach (native)
    at argsert (/home/praveen/npx/node_modules/yargs/lib/argsert.js:42:21)
    at Object.version (/home/praveen/npx/node_modules/yargs/yargs.js:757:5)
    at yargsParser (/home/praveen/npx/parse-args.js:226:4)
    at parseArgs (/home/praveen/npx/parse-args.js:16:18)
    at mockParse (/home/praveen/npx/test/parse-args.js:8:10)
    at Test.t (/home/praveen/npx/test/parse-args.js:102:18)
    at bound (domain.js:280:14)
    at Test.runBound (domain.js:293:12)
    at Test.main (/home/praveen/npx/node_modules/tap/lib/test.js:219:20)
    at TAP.Test.writeSubComment (/home/praveen/npx/node_modules/tap/lib/test.js:354:3)
    at loop (/home/praveen/npx/node_modules/function-loop/index.js:35:15)
    at TAP.Test.runBeforeEach (/home/praveen/npx/node_modules/tap/lib/test.js:678:5)
    at TAP.Test.processSubtest (/home/praveen/npx/node_modules/tap/lib/test.js:318:10)
    # Subtest: uses -p even with -c
        ok 1 - should be equivalent
        ok 2 - should be equivalent
        ok 3 - should be equal
        ok 4 - should be equal
        ok 5 - should be equivalent
        1..5
    ok 10 - uses -p even with -c # time=9.113ms
    
YError: Invalid first argument. Expected boolean or string but received function.
    at argumentTypeError (/home/praveen/npx/node_modules/yargs/lib/argsert.js:65:9)
    at parsed.optional.forEach (/home/praveen/npx/node_modules/yargs/lib/argsert.js:47:39)
    at Array.forEach (native)
    at argsert (/home/praveen/npx/node_modules/yargs/lib/argsert.js:42:21)
    at Object.version (/home/praveen/npx/node_modules/yargs/yargs.js:757:5)
    at yargsParser (/home/praveen/npx/parse-args.js:226:4)
    at parseArgs (/home/praveen/npx/parse-args.js:16:18)
    at mockParse (/home/praveen/npx/test/parse-args.js:8:10)
    at Test.t (/home/praveen/npx/test/parse-args.js:112:18)
    at bound (domain.js:280:14)
    at Test.runBound (domain.js:293:12)
    at Test.main (/home/praveen/npx/node_modules/tap/lib/test.js:219:20)
    at TAP.Test.writeSubComment (/home/praveen/npx/node_modules/tap/lib/test.js:354:3)
    at loop (/home/praveen/npx/node_modules/function-loop/index.js:35:15)
    at TAP.Test.runBeforeEach (/home/praveen/npx/node_modules/tap/lib/test.js:678:5)
    at TAP.Test.processSubtest (/home/praveen/npx/node_modules/tap/lib/test.js:318:10)
    # Subtest: -p prevents command parsing
        ok 1 - should be equal
        ok 2 - should be equivalent
        ok 3 - should be equal
        ok 4 - should be equal
        ok 5 - should be equivalent
        1..5
    ok 11 - -p prevents command parsing # time=10.358ms
    
YError: Invalid first argument. Expected boolean or string but received function.
    at argumentTypeError (/home/praveen/npx/node_modules/yargs/lib/argsert.js:65:9)
    at parsed.optional.forEach (/home/praveen/npx/node_modules/yargs/lib/argsert.js:47:39)
    at Array.forEach (native)
    at argsert (/home/praveen/npx/node_modules/yargs/lib/argsert.js:42:21)
    at Object.version (/home/praveen/npx/node_modules/yargs/yargs.js:757:5)
    at yargsParser (/home/praveen/npx/parse-args.js:226:4)
    at parseArgs (/home/praveen/npx/parse-args.js:16:18)
    at mockParse (/home/praveen/npx/test/parse-args.js:8:10)
    at Test.t (/home/praveen/npx/test/parse-args.js:122:18)
    at bound (domain.js:280:14)
    at Test.runBound (domain.js:293:12)
    at Test.main (/home/praveen/npx/node_modules/tap/lib/test.js:219:20)
    at TAP.Test.writeSubComment (/home/praveen/npx/node_modules/tap/lib/test.js:354:3)
    at loop (/home/praveen/npx/node_modules/function-loop/index.js:35:15)
    at TAP.Test.runBeforeEach (/home/praveen/npx/node_modules/tap/lib/test.js:678:5)
    at TAP.Test.processSubtest (/home/praveen/npx/node_modules/tap/lib/test.js:318:10)
    # Subtest: -- stops option parsing but still does command
        ok 1 - should be equal
        ok 2 - should be equivalent
        ok 3 - should be equal
        ok 4 - should be equal
        ok 5 - should be equivalent
        1..5
    ok 12 - -- stops option parsing but still does command # time=8.874ms
    
YError: Invalid first argument. Expected boolean or string but received function.
    at argumentTypeError (/home/praveen/npx/node_modules/yargs/lib/argsert.js:65:9)
    at parsed.optional.forEach (/home/praveen/npx/node_modules/yargs/lib/argsert.js:47:39)
    at Array.forEach (native)
    at argsert (/home/praveen/npx/node_modules/yargs/lib/argsert.js:42:21)
    at Object.version (/home/praveen/npx/node_modules/yargs/yargs.js:757:5)
    at yargsParser (/home/praveen/npx/parse-args.js:226:4)
    at parseArgs (/home/praveen/npx/parse-args.js:16:18)
    at mockParse (/home/praveen/npx/test/parse-args.js:8:10)
    at Test.t (/home/praveen/npx/test/parse-args.js:132:18)
    at bound (domain.js:280:14)
    at Test.runBound (domain.js:293:12)
    at Test.main (/home/praveen/npx/node_modules/tap/lib/test.js:219:20)
    at TAP.Test.writeSubComment (/home/praveen/npx/node_modules/tap/lib/test.js:354:3)
    at loop (/home/praveen/npx/node_modules/function-loop/index.js:35:15)
    at TAP.Test.runBeforeEach (/home/praveen/npx/node_modules/tap/lib/test.js:678:5)
    at TAP.Test.processSubtest (/home/praveen/npx/node_modules/tap/lib/test.js:318:10)
    # Subtest: -- still respects -p
        ok 1 - should be equal
        ok 2 - should be equivalent
        ok 3 - should be equal
        ok 4 - should be equal
        ok 5 - should be equivalent
        1..5
    ok 13 - -- still respects -p # time=8.645ms
    
YError: Invalid first argument. Expected boolean or string but received function.
    at argumentTypeError (/home/praveen/npx/node_modules/yargs/lib/argsert.js:65:9)
    at parsed.optional.forEach (/home/praveen/npx/node_modules/yargs/lib/argsert.js:47:39)
    at Array.forEach (native)
    at argsert (/home/praveen/npx/node_modules/yargs/lib/argsert.js:42:21)
    at Object.version (/home/praveen/npx/node_modules/yargs/yargs.js:757:5)
    at yargsParser (/home/praveen/npx/parse-args.js:226:4)
    at parseArgs (/home/praveen/npx/parse-args.js:16:18)
    at mockParse (/home/praveen/npx/test/parse-args.js:8:10)
    at Test.t (/home/praveen/npx/test/parse-args.js:142:18)
    at bound (domain.js:280:14)
    at Test.runBound (domain.js:293:12)
    at Test.main (/home/praveen/npx/node_modules/tap/lib/test.js:219:20)
    at TAP.Test.writeSubComment (/home/praveen/npx/node_modules/tap/lib/test.js:354:3)
    at loop (/home/praveen/npx/node_modules/function-loop/index.js:35:15)
    at TAP.Test.runBeforeEach (/home/praveen/npx/node_modules/tap/lib/test.js:678:5)
    at TAP.Test.processSubtest (/home/praveen/npx/node_modules/tap/lib/test.js:318:10)
    # Subtest: allows configuration of npm binary
        ok 1 - should be equal
        1..1
    ok 14 - allows configuration of npm binary # time=5.754ms
    
    # Subtest: treats directory-type commands specially
        ok 1 - should be equal
        ok 2 - should be equivalent
        ok 3 - should be equal
        ok 4 - should be equal
        ok 5 - expect truthy value
YError: Invalid first argument. Expected boolean or string but received function.
    at argumentTypeError (/home/praveen/npx/node_modules/yargs/lib/argsert.js:65:9)
    at parsed.optional.forEach (/home/praveen/npx/node_modules/yargs/lib/argsert.js:47:39)
    at Array.forEach (native)
    at argsert (/home/praveen/npx/node_modules/yargs/lib/argsert.js:42:21)
    at Object.version (/home/praveen/npx/node_modules/yargs/yargs.js:757:5)
    at yargsParser (/home/praveen/npx/parse-args.js:226:4)
    at parseArgs (/home/praveen/npx/parse-args.js:16:18)
    at mockParse (/home/praveen/npx/test/parse-args.js:8:10)
    at Test.t (/home/praveen/npx/test/parse-args.js:154:12)
    at bound (domain.js:280:14)
    at Test.runBound (domain.js:293:12)
    at Test.main (/home/praveen/npx/node_modules/tap/lib/test.js:219:20)
    at TAP.Test.writeSubComment (/home/praveen/npx/node_modules/tap/lib/test.js:354:3)
    at loop (/home/praveen/npx/node_modules/function-loop/index.js:35:15)
    at TAP.Test.runBeforeEach (/home/praveen/npx/node_modules/tap/lib/test.js:678:5)
    at TAP.Test.processSubtest (/home/praveen/npx/node_modules/tap/lib/test.js:318:10)
        ok 6 - should be equal
        ok 7 - expect truthy value
        ok 8 - should be equivalent
        ok 9 - should be equal
        ok 10 - should be equal
        1..10
    ok 15 - treats directory-type commands specially # time=14.503ms
    
YError: Invalid first argument. Expected boolean or string but received function.
    at argumentTypeError (/home/praveen/npx/node_modules/yargs/lib/argsert.js:65:9)
    at parsed.optional.forEach (/home/praveen/npx/node_modules/yargs/lib/argsert.js:47:39)
    at Array.forEach (native)
    at argsert (/home/praveen/npx/node_modules/yargs/lib/argsert.js:42:21)
    at Object.version (/home/praveen/npx/node_modules/yargs/yargs.js:757:5)
    at yargsParser (/home/praveen/npx/parse-args.js:226:4)
    at parseArgs (/home/praveen/npx/parse-args.js:16:18)
    at mockParse (/home/praveen/npx/test/parse-args.js:8:10)
    at Test.t (/home/praveen/npx/test/parse-args.js:166:5)
    at bound (domain.js:280:14)
    at Test.runBound (domain.js:293:12)
    at Test.main (/home/praveen/npx/node_modules/tap/lib/test.js:219:20)
    at TAP.Test.writeSubComment (/home/praveen/npx/node_modules/tap/lib/test.js:354:3)
    at loop (/home/praveen/npx/node_modules/function-loop/index.js:35:15)
    at TAP.Test.runBeforeEach (/home/praveen/npx/node_modules/tap/lib/test.js:678:5)
    at TAP.Test.processSubtest (/home/praveen/npx/node_modules/tap/lib/test.js:318:10)
    # Subtest: -n and --node-arg special parsing rules
        ok 1 - should match pattern provided
YError: Invalid first argument. Expected boolean or string but received function.
    at argumentTypeError (/home/praveen/npx/node_modules/yargs/lib/argsert.js:65:9)
    at parsed.optional.forEach (/home/praveen/npx/node_modules/yargs/lib/argsert.js:47:39)
    at Array.forEach (native)
    at argsert (/home/praveen/npx/node_modules/yargs/lib/argsert.js:42:21)
    at Object.version (/home/praveen/npx/node_modules/yargs/yargs.js:757:5)
    at yargsParser (/home/praveen/npx/parse-args.js:226:4)
    at parseArgs (/home/praveen/npx/parse-args.js:16:18)
    at mockParse (/home/praveen/npx/test/parse-args.js:8:10)
    at Test.t (/home/praveen/npx/test/parse-args.js:170:5)
    at bound (domain.js:280:14)
    at Test.runBound (domain.js:293:12)
    at Test.main (/home/praveen/npx/node_modules/tap/lib/test.js:219:20)
    at TAP.Test.writeSubComment (/home/praveen/npx/node_modules/tap/lib/test.js:354:3)
    at loop (/home/praveen/npx/node_modules/function-loop/index.js:35:15)
    at TAP.Test.runBeforeEach (/home/praveen/npx/node_modules/tap/lib/test.js:678:5)
    at TAP.Test.processSubtest (/home/praveen/npx/node_modules/tap/lib/test.js:318:10)
        ok 2 - should match pattern provided
YError: Invalid first argument. Expected boolean or string but received function.
    at argumentTypeError (/home/praveen/npx/node_modules/yargs/lib/argsert.js:65:9)
    at parsed.optional.forEach (/home/praveen/npx/node_modules/yargs/lib/argsert.js:47:39)
    at Array.forEach (native)
    at argsert (/home/praveen/npx/node_modules/yargs/lib/argsert.js:42:21)
    at Object.version (/home/praveen/npx/node_modules/yargs/yargs.js:757:5)
    at yargsParser (/home/praveen/npx/parse-args.js:226:4)
    at parseArgs (/home/praveen/npx/parse-args.js:16:18)
    at mockParse (/home/praveen/npx/test/parse-args.js:8:10)
    at Test.t (/home/praveen/npx/test/parse-args.js:174:5)
    at bound (domain.js:280:14)
    at Test.runBound (domain.js:293:12)
    at Test.main (/home/praveen/npx/node_modules/tap/lib/test.js:219:20)
    at TAP.Test.writeSubComment (/home/praveen/npx/node_modules/tap/lib/test.js:354:3)
    at loop (/home/praveen/npx/node_modules/function-loop/index.js:35:15)
    at TAP.Test.runBeforeEach (/home/praveen/npx/node_modules/tap/lib/test.js:678:5)
    at TAP.Test.processSubtest (/home/praveen/npx/node_modules/tap/lib/test.js:318:10)
        ok 3 - should match pattern provided
YError: Invalid first argument. Expected boolean or string but received function.
    at argumentTypeError (/home/praveen/npx/node_modules/yargs/lib/argsert.js:65:9)
    at parsed.optional.forEach (/home/praveen/npx/node_modules/yargs/lib/argsert.js:47:39)
    at Array.forEach (native)
    at argsert (/home/praveen/npx/node_modules/yargs/lib/argsert.js:42:21)
    at Object.version (/home/praveen/npx/node_modules/yargs/yargs.js:757:5)
    at yargsParser (/home/praveen/npx/parse-args.js:226:4)
    at parseArgs (/home/praveen/npx/parse-args.js:16:18)
    at mockParse (/home/praveen/npx/test/parse-args.js:8:10)
    at Test.t (/home/praveen/npx/test/parse-args.js:178:5)
    at bound (domain.js:280:14)
    at Test.runBound (domain.js:293:12)
    at Test.main (/home/praveen/npx/node_modules/tap/lib/test.js:219:20)
    at TAP.Test.writeSubComment (/home/praveen/npx/node_modules/tap/lib/test.js:354:3)
    at loop (/home/praveen/npx/node_modules/function-loop/index.js:35:15)
    at TAP.Test.runBeforeEach (/home/praveen/npx/node_modules/tap/lib/test.js:678:5)
    at TAP.Test.processSubtest (/home/praveen/npx/node_modules/tap/lib/test.js:318:10)
        ok 4 - should match pattern provided
YError: Invalid first argument. Expected boolean or string but received function.
    at argumentTypeError (/home/praveen/npx/node_modules/yargs/lib/argsert.js:65:9)
    at parsed.optional.forEach (/home/praveen/npx/node_modules/yargs/lib/argsert.js:47:39)
    at Array.forEach (native)
    at argsert (/home/praveen/npx/node_modules/yargs/lib/argsert.js:42:21)
    at Object.version (/home/praveen/npx/node_modules/yargs/yargs.js:757:5)
    at yargsParser (/home/praveen/npx/parse-args.js:226:4)
    at parseArgs (/home/praveen/npx/parse-args.js:16:18)
    at mockParse (/home/praveen/npx/test/parse-args.js:8:10)
    at Test.t (/home/praveen/npx/test/parse-args.js:182:5)
    at bound (domain.js:280:14)
    at Test.runBound (domain.js:293:12)
    at Test.main (/home/praveen/npx/node_modules/tap/lib/test.js:219:20)
    at TAP.Test.writeSubComment (/home/praveen/npx/node_modules/tap/lib/test.js:354:3)
    at loop (/home/praveen/npx/node_modules/function-loop/index.js:35:15)
    at TAP.Test.runBeforeEach (/home/praveen/npx/node_modules/tap/lib/test.js:678:5)
    at TAP.Test.processSubtest (/home/praveen/npx/node_modules/tap/lib/test.js:318:10)
        ok 5 - should match pattern provided
YError: Invalid first argument. Expected boolean or string but received function.
    at argumentTypeError (/home/praveen/npx/node_modules/yargs/lib/argsert.js:65:9)
    at parsed.optional.forEach (/home/praveen/npx/node_modules/yargs/lib/argsert.js:47:39)
    at Array.forEach (native)
    at argsert (/home/praveen/npx/node_modules/yargs/lib/argsert.js:42:21)
    at Object.version (/home/praveen/npx/node_modules/yargs/yargs.js:757:5)
    at yargsParser (/home/praveen/npx/parse-args.js:226:4)
    at parseArgs (/home/praveen/npx/parse-args.js:16:18)
    at mockParse (/home/praveen/npx/test/parse-args.js:8:10)
    at Test.t (/home/praveen/npx/test/parse-args.js:186:5)
    at bound (domain.js:280:14)
    at Test.runBound (domain.js:293:12)
    at Test.main (/home/praveen/npx/node_modules/tap/lib/test.js:219:20)
    at TAP.Test.writeSubComment (/home/praveen/npx/node_modules/tap/lib/test.js:354:3)
    at loop (/home/praveen/npx/node_modules/function-loop/index.js:35:15)
    at TAP.Test.runBeforeEach (/home/praveen/npx/node_modules/tap/lib/test.js:678:5)
    at TAP.Test.processSubtest (/home/praveen/npx/node_modules/tap/lib/test.js:318:10)
        ok 6 - should match pattern provided
YError: Invalid first argument. Expected boolean or string but received function.
    at argumentTypeError (/home/praveen/npx/node_modules/yargs/lib/argsert.js:65:9)
    at parsed.optional.forEach (/home/praveen/npx/node_modules/yargs/lib/argsert.js:47:39)
    at Array.forEach (native)
    at argsert (/home/praveen/npx/node_modules/yargs/lib/argsert.js:42:21)
    at Object.version (/home/praveen/npx/node_modules/yargs/yargs.js:757:5)
    at yargsParser (/home/praveen/npx/parse-args.js:226:4)
    at parseArgs (/home/praveen/npx/parse-args.js:16:18)
    at mockParse (/home/praveen/npx/test/parse-args.js:8:10)
    at Test.t (/home/praveen/npx/test/parse-args.js:190:5)
    at bound (domain.js:280:14)
    at Test.runBound (domain.js:293:12)
    at Test.main (/home/praveen/npx/node_modules/tap/lib/test.js:219:20)
    at TAP.Test.writeSubComment (/home/praveen/npx/node_modules/tap/lib/test.js:354:3)
    at loop (/home/praveen/npx/node_modules/function-loop/index.js:35:15)
    at TAP.Test.runBeforeEach (/home/praveen/npx/node_modules/tap/lib/test.js:678:5)
    at TAP.Test.processSubtest (/home/praveen/npx/node_modules/tap/lib/test.js:318:10)
        ok 7 - should match pattern provided
YError: Invalid first argument. Expected boolean or string but received function.
    at argumentTypeError (/home/praveen/npx/node_modules/yargs/lib/argsert.js:65:9)
    at parsed.optional.forEach (/home/praveen/npx/node_modules/yargs/lib/argsert.js:47:39)
    at Array.forEach (native)
    at argsert (/home/praveen/npx/node_modules/yargs/lib/argsert.js:42:21)
    at Object.version (/home/praveen/npx/node_modules/yargs/yargs.js:757:5)
    at yargsParser (/home/praveen/npx/parse-args.js:226:4)
    at parseArgs (/home/praveen/npx/parse-args.js:16:18)
    at mockParse (/home/praveen/npx/test/parse-args.js:8:10)
    at Test.t (/home/praveen/npx/test/parse-args.js:194:5)
    at bound (domain.js:280:14)
    at Test.runBound (domain.js:293:12)
    at Test.main (/home/praveen/npx/node_modules/tap/lib/test.js:219:20)
    at TAP.Test.writeSubComment (/home/praveen/npx/node_modules/tap/lib/test.js:354:3)
    at loop (/home/praveen/npx/node_modules/function-loop/index.js:35:15)
    at TAP.Test.runBeforeEach (/home/praveen/npx/node_modules/tap/lib/test.js:678:5)
    at TAP.Test.processSubtest (/home/praveen/npx/node_modules/tap/lib/test.js:318:10)
        ok 8 - should match pattern provided
YError: Invalid first argument. Expected boolean or string but received function.
    at argumentTypeError (/home/praveen/npx/node_modules/yargs/lib/argsert.js:65:9)
    at parsed.optional.forEach (/home/praveen/npx/node_modules/yargs/lib/argsert.js:47:39)
    at Array.forEach (native)
    at argsert (/home/praveen/npx/node_modules/yargs/lib/argsert.js:42:21)
    at Object.version (/home/praveen/npx/node_modules/yargs/yargs.js:757:5)
    at yargsParser (/home/praveen/npx/parse-args.js:226:4)
    at parseArgs (/home/praveen/npx/parse-args.js:16:18)
    at mockParse (/home/praveen/npx/test/parse-args.js:8:10)
    at Test.t (/home/praveen/npx/test/parse-args.js:198:5)
    at bound (domain.js:280:14)
    at Test.runBound (domain.js:293:12)
    at Test.main (/home/praveen/npx/node_modules/tap/lib/test.js:219:20)
    at TAP.Test.writeSubComment (/home/praveen/npx/node_modules/tap/lib/test.js:354:3)
    at loop (/home/praveen/npx/node_modules/function-loop/index.js:35:15)
    at TAP.Test.runBeforeEach (/home/praveen/npx/node_modules/tap/lib/test.js:678:5)
    at TAP.Test.processSubtest (/home/praveen/npx/node_modules/tap/lib/test.js:318:10)
        ok 9 - should match pattern provided
        ok 10 - should match pattern provided
        1..10
    ok 16 - -n and --node-arg special parsing rules # time=63.03ms
    
    1..16
    # time=330.609ms
ok 1 - test/parse-args.js # time=536.608ms

1..1
# time=555.274ms
```

**Comment by harish2704** [comment]
Hi, Please see #140  which fixes the above errors

**Comment by macklinu** [comment]
Looks to be resolved by https://github.com/zkat/npx/commit/0c2314a97e92544613e4413b42ba6db73c19fd35

**Comment by zkat** [comment]
yargs is at 11 now so
