### ISSUE TITLE
i cant install angular in Mac os

### ISSUE THREAD

**Issue by sadin69** [zkat/npx#182]
ABMs-MacBook-Pro:~ abmrocknuzzaman$ sudo npm install -g @angular/cli
Error: EPERM: operation not permitted, mkdir '/usr/abmrocknuzzaman'
TypeError: Cannot read property 'get' of undefined
    at errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:83:20
    at cb (/usr/local/lib/node_modules/npm/lib/npm.js:224:22)
    at /usr/local/lib/node_modules/npm/lib/npm.js:262:24
    at /usr/local/lib/node_modules/npm/lib/config/core.js:81:7
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/npm/lib/config/core.js:80:13
    at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at afterExtras (/usr/local/lib/node_modules/npm/lib/config/core.js:178:20)
    at /usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:35:29
    at /usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53
    at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:284:29
    at FSReqWrap.oncomplete (fs.js:149:21)
/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:205
  if (npm.config.get('json')) {
                 ^

TypeError: Cannot read property 'get' of undefined
    at process.errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at process.emit (events.js:182:13)
    at process._fatalException (internal/bootstrap/node.js:435:27)

**Comment by legodude17** [comment]
You want the [npm issue tracker](https://github.com/npm/npm/issues).

**Comment by sadin69** [comment]
yes pls..... what can i do now....

**Comment by legodude17** [comment]
Report this issue over there. Here is for issues with `npx` not `npm`.
